# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Autotesting

on:
  push:
    branches: ["main", "full-pipe"]

jobs:
  server-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: npm ci and test
        run: | 
          cd server
          npm ci
          npm test

  build:
    runs-on: ubuntu-latest
    needs: server-test

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push server to docker
        uses: docker/build-push-action@v4
        with:
          context: server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ssw-590-final-project:latest-pipe-server
      
      - name: Build and push client to docker
        uses: docker/build-push-action@v4
        with:
          context: client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ssw-590-final-project:latest-pipe-client
      
